language: go
go:
  - 1.8.3
  - 1.9
sudo: false
install:
  - GLIDE_TAG=v0.12.3
  - GLIDE_DOWNLOAD="https://github.com/Masterminds/glide/releases/download/$GLIDE_TAG/glide-$GLIDE_TAG-linux-amd64.tar.gz"
  - curl -L $GLIDE_DOWNLOAD | tar -xvz
  - export PATH=$PATH:$PWD/linux-amd64/
  - mkdir -p $GOPATH/src/github.com/roasbeef/
  - pushd $GOPATH/src/github.com/roasbeef/
  - git clone https://github.com/roasbeef/btcd
  - pushd btcd
  - glide install
  - go install . ./cmd/...
  - popd
  - popd
env:
  global:
    - LOGS=true
  matrix:
    - RACE=false
    - RACE=true
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - ./gotest.sh
after_script:
  - tar -czf "lnd_build_${TRAVIS_BUILD_NUMBER}_logs.tar.gz" output*.log
deploy:
  provider: bintray
  file: "./.bintray_deploy.json"
  user: "sam.vr.lewis@gmail.com"
  key:
    secure: "lKp5D2H3ee0cFhM7xFrOe2tdqNMSymXSttvzesrtc2XNLTkq6b0LQ6sC7cYdKn/CqzOA5lY/ZlSBe7TrGBpfGvw1nswilLCDVRZKvFiE8qlwvZg4fmLZHRQfn6co2KSbOZEHat1+xY3cvt/FY/d1HQ5GdfeQzpCLaM6sr/hTrtVe+q+bGliVWHYBYUfal46tl6ka1VH1TUo0Og++mAT/c92SfVBJlIQm6++z9bbMY6R/lCBsbDmgQTYRgiyvnSsUS8orInyvdnjNRh1mPeNGtKiwFMXRd0SyHNCmpokJf8ez+tSVt4OoRbCRbAFOUO6g2Owf/8opNf5yLT1IZ3L49xW6e9dKO7hPOofH8J4YAz2r64ZGeTca2TGRBKw+ADK3gfVlPPP2aMGP7b8j9GMJ0xgyojz2brkf3gJRJQgsRTZ4HP4eR8AA++N6bVK5ib2uAN7MTtr3zKrlPg9thyf3LRjWPfMzOjgWO7pojpyeGSEiPxSF0/tR5XxykeruT1RI0zxISTxEVnow5DxLKUDBl24wdW0Z6ClVxfABBO0b+0kuhdiC3OEDJj8yPjKeY+QuLezQij8O9QmzzYtorKd/FJF5iTGnw2uj/miuoEGj8/1wXQ0YDprM5u+3VJN5DwOR5aIL7wfeJ8IYKQyieLtMbaty3nof7TqKLvRCEX8oLXw="
  on:
    all_branches: true