language: go
go:
  - 1.8.3
  - 1.9
sudo: false
install:
  - GLIDE_TAG=v0.12.3
  - GLIDE_DOWNLOAD="https://github.com/Masterminds/glide/releases/download/$GLIDE_TAG/glide-$GLIDE_TAG-linux-amd64.tar.gz"
  - curl -L $GLIDE_DOWNLOAD | tar -xvz
  - export PATH=$PATH:$PWD/linux-amd64/
  - mkdir -p $GOPATH/src/github.com/roasbeef/
  - pushd $GOPATH/src/github.com/roasbeef/
  - git clone https://github.com/roasbeef/btcd
  - pushd btcd
  - glide install
  - go install . ./cmd/...
  - popd
  - popd
env:
  global:
    - LOGS=true
  matrix:
    - RACE=false
    - RACE=true
deploy:
  provider: bintray
  file: "Path to a descriptor file, containing information for the Bintray upload"
  user: "Bintray user"
  key: "Bintray API key"
  passphrase: "Optional. In case a passphrase is configured on Bintray and GPG signing is used"
  dry-run: "Optional. If true, skips sending requests to Bintray. Useful for testing your configuration
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - ./gotest.sh
after_script:
  - tar -czf "lnd_build_${TRAVIS_BUILD_NUMBER}_logs.tar.gz" output*.log
